# Checks that the build of the current branch succeeds

name: build

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        type: text
        default: 'Manual run'
      configuration:
        description: 'The project configuration to run the workflow using'
        required: true
        type: choice
        options:
          - Release
          - Debug
        default: Release
  push:
    paths:
    - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/**'

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

jobs:
  build:
    name: build-${{matrix.os}}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: 'Print manual run information'
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Reason: ${{ inputs.reason }}`nConfiguration: ${{ inputs.configuration }}"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ inputs.configuration }} --no-restore
